- hosts: all

  tasks:
    - name: Run do-it.sh
      shell:
        cmd: |
          set -e
          set -x
          export TEMPDIR=${TEMPDIR:-$(mktemp -d $(pwd)/dmtmp-XXXXXX)}
          export GITBASE=${TEMPDIR}/git
          export LP_STATS=n
          bash ./do-it.sh
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
